* ideas
** Marx was the better Nietzschean -- this could be the core of a paper
Nietzsche writes in Human All Too Human, ``Es ist wahrscheinlich, dass
die Objekte des religiösen, moralischen und ästhetischen Empfindens
ebenfalls nur zur Oberfläche der Dinge gehören, während der Mensch
gerne glaubt, dass er hier wenigstens an das Herz der Welt rühre; er
täuscht sich ...'' I claim that Nietzsche himself made this mistake.
His criticism of Christianity is fixated on religion and psychology,
when the underlying culprit is economic relations. Nietzsche ist hier
den Christen auf denselben Leim gegangen, auf den sich die Christen
selber gehen: n"amlich dass Religion und Psychologie die Gef"uhle
erkl"aren. Religion and psychology, however, are side effects of the
emotional medicine (or drug addiction) that the systemic unease in our
economic relations requires. Nietzsche's ressentiment is much better
explained by Marx than by Nietzsche. This is why Kropotkin's mutual
aid is a far superior candidate for easing the suffering of modernity
than Kammerzell's intimacy, which only reinforces it. <2018-04-17 Tue>
** parfit module
https://www.newyorker.com/magazine/2011/09/05/how-to-be-good
Simon Blackburn's review of On What Matters
** first research
Nietzsche's system John Richardson [recalled]

Nietzsche on Morality B Leiter [available UBC Lib online]

Nietzsche
Edited by John Richardson and Brian Leiter

Nietzsche and Morality
Edited by Brian Leiter and Neil Sinhababu [requested]

https://www.gc.cuny.edu/CUNY_GC/media/CUNY-Graduate-Center/PDF/Programs/Philosophy/Leiter-NIETZSCHE.pdf

Maudemarie Clark & David Dudrick, The Soul of Nietzsche's Beyond Good
and Evil  [available UBC Lib online]

Christopher Janaway, Beyond Selflessness:  Reading Nietzsche's
Genealogy [requested]

Paul Katsafanas, "Nietzsche's Philosophical Psychology," [article dnl]

Mattia Riccardi, "Inner Opacity:  Nietzsche on Introspection and
Agency," Inquiry 58 (2015):  221-243 [article dnl]
** feedback PHIL 375 Hermeneutics Fall 2017
perhaps no more iClickers? use index cards instead

talk about the text that was due TODAY

give out essay questions earlier
** outline
Nietzsche and Foucault (genealogy)

Nietzsche and Gender

Nietzsche and Naturalism/Existentialism

Nietzsche and Personal Identity

Nietzsche and Bernard Williams

Nietzsche and Hermeneutics

Nietzsche and Morality

Nietzsche and Marx

Nietzsche and Freud
* Nietzsche Readings
** notes
Daybreak, book 1, 2, 3

Human, All Too Human, book 1 (up to 53 inclusive); book 3 is short,
good , and about philosophy of religion

Gay Science

Genealogy of Morals book 1, 2

Beyond Good and Evil
** Human, All Too Human
preface, book 1 (up to 53 inclusive)
* potential nietzsche paper
** astrology
[Friedrich Nietzsche and David Short: never hesitate to pronounce the
truth of a non-scientific proposition]

Excerpts from Friedrich Nietzsche, Daybreak, 207, with
astrological signs replacing national identities (in particular,
Gemini for German).

A Gemini is capable of great things but he is unlikely to
accomplish them, for he obeys whenever he can as suits a naturally
lazy intellect. If he is ever in the dangerous situation of having
to stand alone and cast aside his sloth when he finds it no longer
possible to disappear like a cipher in a number (in which respect
he is far inferior to a Sagittarius or an Aries) he shows his true
strength: then he becomes dangerous, evil, deep, and audacious,
and exhibits to the light of day that wealth of latent energy
which he had previously carried hidden in himself and in which no
one not even himself had ever believed.

When in such a case a Gemini obeys himself---it is very exceptional
for him to do so---he does so with the same heaviness, inflexibility,
and endurance with which he obeys his boss and performs his
official duties: so that as I have said he is then capable of
great things which bear no relation to the ``weak disposition'' he
attributes to himself. As a rule, however, he is afraid of depending
upon himself alone, he is afraid of taking the initiative.

Light-heartedness is a stranger to the Gemini; he is too timid for
it: but in entirely new situations which rouse him from his torpor
he exhibits an almost frivolous spirit. He then delights in the
novelty of his new position as if it were some intoxicating drink
and he is as we know quite a connoisseur in intoxication. 

It thus happens that the Gemini of the present day is almost
always frivolous in politics though even here he has the advantage
and prejudice of thoroughness and seriousness; he rejoices
inwardly at being able for once in his life to feel enthusiastic
and capricious to show his fondness for innovations and to change
persons parties and hopes as if they were masks.

When a Gemini ever did anything great it was done at a time of
danger or when his courage was high with his teeth firmly set and
his prudence on the alert and often enough in a fit of generosity.
Intercourse with these Geminis is indeed advisable for almost
every one of them has something to give if we can only understand
how to make him find it or rather recover it (for he is very
untidy in storing away his knowledge). 
* annotation for articles/books
** Alexander Nehamas
** Edward Craig: Genealogies and the State of Nature
** B2 Raymond Geuss: Nietzsche and Genealogy
On the one hand, it's short and talks about an intensely important
topic. On the other hand, it doesn't have much to say and spends too
much time on Paul and Jesus. 
** B1 Hurka, Nietzsche: Perfectionist
good, stimulating paper about maximax and perfectionism; I like
Hurka's approach (a bit like Parfit), where you make Nietzsche say
what YOU believe; disinclined to assign but it's a possibility
** B1 Reginster, The Will to Power and the Ethics of Creativity
pretty good, especially the part about creativity; disinclined to assign but it's a possibility
** Risse, Nietzschean Animal Psychology versus Kantian Ethics
** Janaway, Guilt, Bad Conscience, and Self-punishment in Nietzsche's Genealogy
** Poellner, Affect, Value and Objectivity
** Sinhababu, Vengeful Thinking and Moral Epistemology.
** B1 Nancy Love: The Problem of Modernity
Chapter One of Marx, Nietzsche, and Modernity, pages 1--18
** A3 Karl Marx, Vorwort zu Zur Kritik der Politischen Ökonomie
Preface to a Contribution to the Critique of Political Economy
http://mlwerke.de/me/me13/me13_007.htm
this and the Communist Manifesto may be the best Marx readings
passages about alienation?
** A3 Jay Wallace,Ressentiment
strong paper, disagree with some conclusions, assign in the Marx module
** A3 Paul Katsafanas,Nietzsches Philosophical Psychology
Good paper; an analysis of Nietzsche's drive psychology. Can't think
of a category to assign, may be too technical anyways.
** A2 Brian Leiter,The Paradox of Fatalism and Self Creation in Nietzsche
Separate category for naturalism or fatalism? Assign. With Dostoevsky
and Sartre?
** B1 Brian Leiter,Nietzsches Naturalistic Moral Psychology
B+. No good category for it. Don't assign.
** A2 Mattia Riccardi,Inner Opacity Nietzsche on Introspection and Agency
Excellent article. Assign in the Freud module.
* Nietzsche Werke
(pdf) Die Geburt der Tragödie
(   ) Unzeitgemässe Betrachtungen
(txt) Menschliches, Allzumenschliches
(txt) Morgenröthe
(txt) Die fröhliche Wissenschaft
(txt) Also sprach Zarathustra
(txt) Jenseits von Gut und Böse
(txt) Zur Genealogie der Moral
(   ) Der Wille zur Macht
(txt) Götzendämmerung
(txt) Der Antichrist
(   ) Dionysos-Dithyramben
(   ) Der Fall Wagner
(   ) Nietzche contra Wagner
(txt) Ecce homo
* buffer
